server: 
  port: 60
  context-path: #/yl/

spring:  
  mvc: 
    view: 
      prefix: /WEB-INF/
      suffix: .ftl
  freemarker:
      cache: true
      request-context-attribute: request
      charset: UTF-8
#      template-loader-path: classpath:/templates/
  
#  resources:
#    static-locations: classpath:/webapp/
    
   
    
      
      
